mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-apt', '4.5.1'
mod 'puppetlabs-concat', '4.2.1'
mod 'puppet-yum', '2.2.1'
mod 'elastic-elastic_stack', '6.1.0'
mod 'elastic-logstash', '6.1.2'
mod 'elastic-kibana', '6.0.1'
mod 'richardc-datacat', '0.6.2'
mod 'elastic-elasticsearch', '6.2.2'
mod 'ingernet-elk', :git => 'https://github.com/ingernet/ingernet-elk.git'
